--- 
- hosts: all 
  become: yes
  tasks: 
    - names: i want to install apache2 webserver on redhat
      yum: 
      name: apache2
      state: present

    - name: i want to start apache2 webserver on amazon linux
      service: 
         name: apache2
         state:  started
         