---
- name: Install apache server   
  hosts: ec2    
  become: yes
  tasks:
    - name: install apache server   
      yum:
        name: httpd
        state: latest
        update_cache: yes
    - name: start and enable autostart of apache server
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: i want to install httpd webserver on RedHat 
      dnf :
        name: httpd 
        state: present 
      when: ansible_os_family=="RedHat" 

    - name: i want to start httpd webserver on RedHat 
      service: 
        name: httpd 
        state: started 
      when: ansible_os_family=="RedHat"     