---
- name: Install Apache HTTP Server on Amazon Linux
  hosts: your_amazon_linux_servers
  become: yes
  tasks:
    - name: Install Apache package
      package:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: i want to install httpd webserver on Redhat 
      dnf :
        name: httpd 
        state: present 
      when: ansible_os_family=="Redhart" 
       
    - name: i want to start httpd webserver on Redhat 
      service: 
        name: httpd 
        state: started 
      when: ansible_os_family=="Redhat"     