--- 
- name: Install Apache HTTP Server on Amazon Linux
  hosts: your_amazon_linux_servers
  become: yes
  tasks:
    - name: Install Apache package
      package:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
