---
- name: i want to install httpd webserver on RedHat
  hosts: your_amazon_linux_servers
  become: yes
  tasks:
    - name: Install Apache package
      package:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: i want to install httpd webserver on RedHat 
      dnf :
        name: httpd 
        state: present 
      when: ansible_os_family=="RedHat" 

    - name: i want to start httpd webserver on RedHat 
      service: 
        name: httpd 
        state: started 
      when: ansible_os_family=="RedHat"     